package gov.usgs.cida.coastalhazards.rest.publish;

import com.sun.jersey.api.core.PackagesResourceConfig;
import java.util.HashMap;
import java.util.Set;
import javax.ws.rs.ApplicationPath;

/**
 *
 * @author Jordan Walker <jiwalker@usgs.gov>
 */
@ApplicationPath("/publish")
public class PublishRestApplication extends PackagesResourceConfig {

	public PublishRestApplication() {
		super(new HashMap<String, Object>() {
			private static final long serialVersionUID = 76876L;
			{
				put(PackagesResourceConfig.PROPERTY_PACKAGES, this.getClass().getPackage().getName());
			}
		});
	}

	@Override
	public Set<Class<?>> getClasses() {
		Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
		addRestResourceClasses(resources);
		return resources;
	}

	/**
	 * Do not modify addRestResourceClasses() method.
	 * It is automatically re-generated by NetBeans REST support to populate
	 * given list with all resources defined in the project.
	 */
	private void addRestResourceClasses(Set<Class<?>> resources) {
		resources.add(gov.usgs.cida.coastalhazards.oid.session.SessionResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.ActivityResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.ItemResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.MetadataResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.MinifyResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.SLDResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.data.SessionResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.publish.PublishResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.ui.InfoRouter.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.ui.ItemRouter.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.ui.TestResource.class);
		resources.add(gov.usgs.cida.coastalhazards.rest.ui.ViewRouter.class);
	}
}
